api_product_get_list:
  path: /api/clientes
  controller: App\Controller\Api\ClienteApiController::getList
  methods: [GET]

api_product_get_one:
  path: /api/clientes/{id}
  controller: App\Controller\Api\ClienteApiController::getOne
  methods: [GET]

api_product_create:
  path: /api/clientes
  controller: App\Controller\Api\ClienteApiController::create
  methods: [POST]  

api_product_remove:
  path: /api/clientes/{id}
  controller: App\Controller\Api\ClienteApiController::remove
  methods: [DELETE]    

api_product_update:
  path: /api/clientes/{id}
  controller: App\Controller\Api\ClienteApiController::update
  methods: [PATCH]  

 